### ISSUE TITLE
DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.

### ISSUE THREAD

**Issue by silverwind** [xz64/license-webpack-plugin#89]
I've seen this one before and you can probably fix it by using `compilation.emitAsset` like I did [here](https://github.com/sindresorhus/add-asset-webpack-plugin/commit/2068887aaa78c127de7027116db7a8858cc6f2b8#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346).

````
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
  Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
  Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    at WebpackAssetManager.writeAllLicenses (node_modules/license-webpack-plugin/dist/WebpackAssetManager.js:31:42)
    at node_modules/license-webpack-plugin/dist/WebpackCompilerHandler.js:50:40
    at Hook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.emitAssets (node_modules/webpack/lib/Compiler.js:808:19)
    at node_modules/webpack/lib/Compiler.js:413:10
    at processTicksAndRejections (node:internal/process/task_queues:75:11)
````

**Comment by xz64** [comment]
This seems to happen when `perChunkOutput: false` is used with webpack 5. 
I think your suggestion will cause issue #83 to occur again since it will emit the same asset from multiple different compilations.

The challenge is due to this:
1. Some webpack builds produce multiple compilation objects
2. When perChunkOutput is set to false, the same license file is written multiple times via different compilations (i.e. calling `compilation.assets[filename] = ...` multiple times), which causes issue #83 
3. There doesn't seem to be a way to hook into webpack before the compilation is sealed, yet after all the compilations have been visited. Each compilation flows independently through the plugin.

I could also fix it by emitting a separate license file per compilation, but that's probably not how people expect it to work.

I'll see if I can come up with any other ideas.

**Comment by silverwind** [comment]
Yes, I have `perChunkOutput` disabled. I recall it was to avoid another error related to [child compilers](https://github.com/microsoft/monaco-editor-webpack-plugin). Full config is [here](https://github.com/go-gitea/gitea/blob/87a0396719dc12a19e9876bd4e5ba6ea008072d8/webpack.config.js#L262-L286) for reference.

One think I've also noticed with webpack 5 is that the produced license file shrunk from 110kB to 40kB so it might be missing some modules, need to check further.

**Comment by xz64** [comment]
If perChunkOutput is set to false, I could also write the file just using plain old `fs` module. This is how the plugin worked in versions < 1.x.
What do you think?

**Comment by silverwind** [comment]
Hmm that would mean it no longer shows up in asset stats, right? Not sure I like that, because it's a nice verification to check the stats if it was written.

**Comment by silverwind** [comment]
Maybe you can take a hint from https://github.com/microsoft/license-checker-webpack-plugin, it seems to worked fine in my testing in this regard.

**Comment by xz64** [comment]
Thanks for the link. For now I reverted the change from #83, so I will reopen #83 and close this one.

**Comment by silverwind** [comment]
Thanks, compilation now works without errors/warnings for me. As for the issue with missing modules, I'm investigating.
